#!/bin/sh

# SPDX-FileCopyrightText: 2024 The rsinit Authors
# SPDX-License-Identifier: GPL-2.0-only

export RUSTFLAGS="-Zfmt-debug=none -C target-feature=+crt-static"
exec cargo +nightly "${@}" --profile minimal -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
