# SPDX-FileCopyrightText: 2024 The rsinit Authors
# SPDX-License-Identifier: GPL-2.0-only

[package]
name = "rsinit"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"
description = "minimalistic single binary initramfs init for embedded systems"
homepage = "https://github.com/michaelolbrich/rsinit"
repository = "https://github.com/michaelolbrich/rsinit"
keywords = ["initramfs", "init", "rdinit"]
categories = ["embedded"]
readme = "README.md"

[[bin]]
name = "init"
path = "src/main.rs"

[dependencies]
nix = { version = "0.30.1", features = ["fs", "mount", "process", "term"], default-features = false }
getrandom = { version = "0.2.15" }
log = { version = "0.4.21", features = ["std"], default-features = false}

[features]
default = ["systemd", "dmverity", "usb9pfs", "reboot-on-failure"]
systemd = ["nix/reboot"]
dmverity = ["nix/ioctl"]
usb9pfs = []
reboot-on-failure = ["nix/reboot"]

[profile.release]
opt-level = 'z'
strip = true
lto = "fat"
incremental = false
codegen-units = 1

[profile.minimal]
inherits = "release"
panic = "abort"
